### ISSUE TITLE
Build modal pattern

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-dashboard-theme#10]
Design spec: https://github.com/ubuntudesign/vanilla-dashboard-theme-design/tree/master/Modal%20window

**Comment by anthonydillon** [comment]
What is the transparency level of the background?

**Comment by richmccartney** [comment]
Most modals have a title or description, can we incorporate that too https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role

**Comment by richmccartney** [comment]
@spencerbygraves ^

**Comment by spencerbygraves** [comment]
Thanks @anthonydillon @richmccartney I've updated the specs and png.
